CREATE TABLE Person(
                       id int PRIMARY KEY,
                       name varchar,
                       phone varchar,
                       bot_state varchar
);

CREATE TABLE Request(
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar,
                        phone_number varchar,
                        time timestamp
);